language: node_js
node_js:
  - "12"
  - "14"
  - "lts/*"
  - "node" #temp
  #cache:
  #directories:
  #  - "node_modules"

install:
  npm install --cache /tmp
branches:
  only:
  - master
before_script: npm run build 
script: npm test
